### ISSUE TITLE
Update landing page to reflect political properties of the tech stack

### ISSUE THREAD

**Issue by tao-oat** [Wobbly-App/wobbly.app#21]
The fact that Wobbly can federate is a really important point, especially to the type of people who might be interested in syndicalist organizing. Similarly, the fact that it's built on open standards (XMPP).

I think we should highlight these things on the landing page. Maybe under the "Organisation over mobilisation" section, we could add a section along the lines of

> **Open, encrypted, and federated**
> 
> Wobbly is free software built on open standards. Messages are end-to-end encrypted so servers cannot read your messages -- and if you still don't trust someone else's server, you can host your own while still organizing with others.

cc/ @King-Mob

**Comment by King-Mob** [comment]
Yes, this is an important point. Fully on board with adding that verbatim.
